apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-auto-arch-certificate
spec:
  secretName: k8s-auto-arch
  dnsNames:
  - k8s-auto-arch.kube-system.svc
  - k8s-auto-arch.kube-system
  issuerRef:
    name: selfsigned
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
