kind: MutatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: pod-label-add
webhooks:
  - name: pod-label-add.trstringer.com
    failurePolicy: Ignore
    clientConfig:
      url: https://mutate.local.ongy.net/k8s-auto-arch
#      service:
#        namespace: default
#        name: mutating-webhook
#        path: /mutate
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        operations: ["CREATE"]
        scope: "*"
    sideEffects: None
    admissionReviewVersions: ["v1"]
