kind: Deployment
apiVersion: apps/v1
metadata:
  name: k8s-auto-arch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-auto-arch
  template:
    metadata:
      labels:
        app: k8s-auto-arch
    spec:
      containers:
        - name: mutating-webhook
          command:
          - /k8s-auto-arch
          args:
          - --logtostderr=true
          - -v=3
          - --otlp_collector=my-release-signoz-otel-collector.signoz:4317
          image: cr.local.ongy.net/ongy/k8s-auto-arch:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ['ALL']
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            runAsUser: 10001
            runAsGroup: 10001