kind: Deployment
apiVersion: apps/v1
metadata:
  name: k8s-auto-arch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-auto-arch
  template:
    metadata:
      labels:
        app: k8s-auto-arch
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: tls-cert
        secret:
          secretName: k8s-auto-arch
      containers:
        - name: mutating-webhook
          command:
          - /k8s-auto-arch
          args:
          - --tls-key=/tls/tls.key
          - --tls-crt=/tls/tls.crt
          image: cr.local.ongy.net/ongy/k8s-auto-arch:arm64
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ['ALL']
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            runAsUser: 10001
            runAsGroup: 10001
          volumeMounts:
          - name: tls-cert
            mountPath: /tls/
            readOnly: true